### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by spideyroc1** [Slikey/EffectLib#23]
Here is my code, i get an internal error occurred when attempting to perform that command..

package net.parkourworld.helix;

import java.util.List;
import java.util.ArrayList;

import de.slikey.effectlib.EffectManager;
import de.slikey.effectlib.Effect;
import de.slikey.effectlib.EffectLib;
import de.slikey.effectlib.effect.HelixEffect;
import de.slikey.effectlib.util.DynamicLocation;

import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.plugin.Plugin;
import org.bukkit.plugin.java.JavaPlugin;

public class main extends JavaPlugin{
	
	
	
	
	
	public void onEnable(){
	    if (Bukkit.getPluginManager().getPlugin("EffectLib") != null)
	    {
	      this.lib = EffectLib.instance();
	    }
	}
	
	
	private Object lib;
	
	EffectManager em = new EffectManager((Plugin)this.lib);
	
	List<String> toggled = new ArrayList<String>();
	public boolean onCommand(CommandSender sender, Command command, String label, String[] args){
		if (label.equalsIgnoreCase("helix")){
			if (!(sender instanceof Player)) {
				sender.sendMessage("You must be a player.");
				return false;
			}
			Player player = (Player) sender;
			if (toggled.contains(player.getName())){
				player.sendMessage("Helix OFF");
				toggled.remove(player.getName());
				return true;
			}
			player.sendMessage("Helix ON");
			toggled.add(player.getName());
			Location loc = player.getLocation();
			Effect effect = new HelixEffect(em);
			effect.setDynamicOrigin(new DynamicLocation(loc));
			effect.start();
			
	        return true;
	    }
		
		return false;
	}
	public void onRun() {
		// TODO Auto-generated method stub
		
	}

}

And here is the console log:
[08:58:44 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'heli
x' in plugin helix v1.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spi
got.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:14
1) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServe
r.java:641) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerCon
nection.java:1162) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java
:997) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java
:45) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java
:1) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:1
3) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_66]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_66]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar
:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:7
15) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
74) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:6
54) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:557) [spigot.jar:git-Spigot-5f38d38-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.IllegalArgumentException: Plugin cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot.
jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.validate(Craf
tScheduler.java:397) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.runTaskTimer(
CraftScheduler.java:123) ~[spigot.jar:git-Spigot-5f38d38-18fbb24]
        at de.slikey.effectlib.EffectManager.start(EffectManager.java:74) ~[?:?]

        at de.slikey.effectlib.Effect.start(Effect.java:223) ~[?:?]
        at net.parkourworld.helix.main.onCommand(main.java:57) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spi
got.jar:git-Spigot-5f38d38-18fbb24]
        ... 15 more

**Comment by JeromSar** [comment]
`Caused by: java.lang.IllegalArgumentException: Plugin cannot be null`

Seems like this is your issue. Are you sure `this.lib` refers to a non-null object in `EffectManager em = new EffectManager((Plugin)this.lib);`?

**Comment by NathanWolf** [comment]
Agreed - try initializing the EffectManager in onEnable, after you've set the "lib" reference.

**Comment by spideyroc1** [comment]
Ok, so I actually have no idea what i am doing, I am just trying to mess with examples from different posts on bukkit and stuff. Can someone show me an example on how to make a helix particle around the player. I am brand new to the bukkit api and java, and I am basically just fiddling with particles. I don't really understand this totally yet.

**Comment by spideyroc1** [comment]
Ok, so I finally got a plugin to work, but wow does it just lag my server all day even when its not online, anyone know why?
package net.parkourworld.helix;

import java.util.List;
import java.util.ArrayList;


import de.slikey.effectlib.EffectManager;
import de.slikey.effectlib.Effect;
import de.slikey.effectlib.EffectLib;
import de.slikey.effectlib.util.DynamicLocation;
import de.slikey.effectlib.effect.VortexEffect;

import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.plugin.java.JavaPlugin;

public class main extends JavaPlugin{
	EffectManager em = new EffectManager(EffectLib.instance());
	
	public void onEnable(){
	    if (Bukkit.getPluginManager().getPlugin("EffectLib") != null)
	    {
	      
	    }
	}
	public void onDisable(){
		em.dispose();
	}
	
	
	
	
	List<String> toggled = new ArrayList<String>();
	public boolean onCommand(CommandSender sender, Command command, String label, String[] args){
		if (label.equalsIgnoreCase("helix")){
			if (!(sender instanceof Player)) {
				sender.sendMessage("You must be a player.");
				return false;
			}
			Player player = (Player) sender;
			if (toggled.contains(player.getName())){
				player.sendMessage("Helix OFF");
				toggled.remove(player.getName());
				return true;
			}
			player.sendMessage("Helix ON");
			toggled.add(player.getName());
			Location loc = player.getLocation();
			Effect effect = new VortexEffect(em);
			effect.setDynamicOrigin(new DynamicLocation(loc));
			effect.start();
			
	        return true;
	    }
		return false;
	}

}

**Comment by NathanWolf** [comment]
You still want to initialize in onEnable, try adding EffectLib to "depends" in your plugin.yml to make sure it loads before your plugin.

You should use a HashSet rather than ArrayList for your toggled set.

As for the lag, I can't account for that. Try running a timings - EffectLib does nothing on its own.
