### ISSUE TITLE
Error Plugin already initialized!

### ISSUE THREAD

**Issue by SnakerCZ** [Slikey/EffectLib#51]
Hi,
when im starting server with EffectLib, EffectLib can't load and i get this error:

`[11:44:16] [Server thread/ERROR]: Could not load 'plugins/EffectLib-6.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[server.jar:git-Spigot-65a0347-a552117]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[server.jar:git-Spigot-65a0347-a552117]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [server.jar:git-Spigot-65a0347-a552117]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:301) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [server.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [server.jar:git-Spigot-65a0347-a552117]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:122) ~[server.jar:git-Spigot-65a0347-a552117]
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:67) ~[server.jar:git-Spigot-65a0347-a552117]
	at de.slikey.effectlib.EffectLib.<init>(EffectLib.java:126) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_101]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_101]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[server.jar:git-Spigot-65a0347-a552117]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[server.jar:git-Spigot-65a0347-a552117]
	... 6 more
Caused by: java.lang.IllegalStateException: Initial initialization
	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:125) ~[server.jar:git-Spigot-65a0347-a552117]
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:67) ~[server.jar:git-Spigot-65a0347-a552117]
	at com.hotmail.AdrianSRJose.AnniPro.main.AnnihilationMain.<init>(AnnihilationMain.java:57) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_101]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_101]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[server.jar:git-Spigot-65a0347-a552117]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[server.jar:git-Spigot-65a0347-a552117]
	... 6 more`

Version: Spigot 1.11.2
Plugins: [11:57:04 INFO]: Plugins (35): WorldEdit, DoubleJump, Skript, PlaceholderAPI, PlugMan, AutoMessage, ColorMOTD, SkQuery, AnnihilationWorldRestorerLite, Votifier, RewardPRO, WorldGuard, Multiverse-Core, SkinsRestorer, PermissionsEx, AnnihilationLite, ViaVersion, Vault, DailyRewards, ViaBackwards, ViaRewind, BlockParticles, UltraCosmetics, Essentials, RegionFX, TNTRun, SkAction, ProtocolLib, Citizens, CommandNPC, EssentialsSpawn, AuthMe, HolographicDisplays, skRayFall, Clockdisplay

Why this happens and how i can repair it? It really affects development of my server... Thanks :)

**Comment by NathanWolf** [comment]
Is this your plugin?
`com.hotmail.AdrianSRJose.AnniPro.main.AnnihilationMain`

It looks like it's doing something along the lines of new EffectLib (creating an instance of the plugin) which it should not be doing.
