### ISSUE TITLE
1.13 support

### ISSUE THREAD

**Issue by mixxit** [Slikey/EffectLib#52]
```
de.slikey.effectlib.util.ParticleEffect$ParticlePacket$VersionIncompatibleException: Your current bukkit version seems to be incompatible with this library
        at de.slikey.effectlib.util.ParticleEffect$ParticlePacket.initialize(ParticleEffect.java:1223) ~[?:?]
        at de.slikey.effectlib.EffectManager.<init>(EffectManager.java:47) ~[?:?]
        at com.solinia.solinia.Solinia3CorePlugin.onEnable(Solinia3CorePlugin.java:143) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_13_R2.EnumParticle
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
        at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_181]
        at de.slikey.effectlib.util.ReflectionUtils$PackageType.getClass(ReflectionUtils.java:412) ~[?:?]
        at de.slikey.effectlib.util.ParticleEffect$ParticlePacket.initialize(ParticleEffect.java:1180) ~[?:?]
        ... 13 more
```

**Comment by mixxit** [comment]
updated to 6.1
